---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-ns.yaml
  - 1-rhel-entitlement-shared-resource.yaml
  - 2-rhel-entitlement-role.yaml
  - 3-rhel-entitlement-role-binding.yaml
  - 4-rhel-entitlement-cluster-role.yaml
  - 5-role-binding-builds.yaml
...
